@extends('layouts.app')
@section('content')
<div class="content">
    <div class="headline"><div><div class="eyebrow">Administrasi</div><h1>Riwayat absensi</h1></div><div class="date">Pantau kehadiran pegawai</div></div>
    <section class="panel">
        <div style="display:flex;justify-content:flex-end;margin-bottom:14px"><form method="GET" action="{{ route('attendance.export') }}" style="display:flex;gap:8px;align-items:center"><input type="month" name="month" value="{{ request('month', now()->format('Y-m')) }}" class="filter-month"><button class="btn btn-light">Export CSV bulanan</button></form></div>
        <form class="filter" method="GET" style="display:grid;grid-template-columns:1.2fr 1fr 1fr 1fr auto;gap:10px;align-items:end;margin-bottom:24px"><div><label>Pegawai</label><select class="form-control" name="employee"><option value="">Semua pegawai</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected(request('employee') == $employee->id)>{{ $employee->name }}</option>@endforeach</select></div><div><label>Dari tanggal</label><input class="form-control" type="date" name="from" value="{{ request('from') }}"></div><div><label>Sampai tanggal</label><input class="form-control" type="date" name="to" value="{{ request('to') }}"></div><div><label>Status</label><select class="form-control" name="status"><option value="">Semua status</option><option @selected(request('status') === 'Hadir')>Hadir</option><option @selected(request('status') === 'Terlambat')>Terlambat</option></select></div><button class="btn btn-primary">Filter</button></form>
        <div class="table-wrap"><table><thead><tr><th>Tanggal</th><th>Pegawai</th><th>Masuk</th><th>Pulang</th><th>Lokasi GPS</th><th>Status</th></tr></thead><tbody>
        @forelse($attendances as $item)
            <tr><td>{{ $item->date->format('d M Y') }}</td><td>{{ $item->user->name }}</td><td class="{{ $item->status === 'Terlambat' ? 'time-late' : '' }}">{{ $item->check_in?->format('H:i') ?? '—' }}</td><td>{{ $item->check_out?->format('H:i') ?? '—' }}</td><td class="location-links">@if($item->check_in_latitude !== null)<a href="https://www.google.com/maps/search/?api=1&query={{ $item->check_in_latitude }},{{ $item->check_in_longitude }}" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 21s7-6.1 7-12A7 7 0 0 0 5 9c0 5.9 7 12 7 12Z"/><circle cx="12" cy="9" r="2.2"/></svg><span>Masuk: {{ $item->check_in_latitude }}, {{ $item->check_in_longitude }}</span></a>@endif @if($item->check_out_latitude !== null)<a href="https://www.google.com/maps/search/?api=1&query={{ $item->check_out_latitude }},{{ $item->check_out_longitude }}" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 21s7-6.1 7-12A7 7 0 0 0 5 9c0 5.9 7 12 7 12Z"/><circle cx="12" cy="9" r="2.2"/></svg><span>Pulang: {{ $item->check_out_latitude }}, {{ $item->check_out_longitude }}</span></a>@endif @if($item->check_in_latitude === null && $item->check_out_latitude === null)—@endif</td><td><span class="pill {{ $item->status === 'Terlambat' ? 'late' : '' }}">{{ $item->status }}</span></td></tr>
        @empty
            <tr><td colspan="6" class="muted">Belum ada data sesuai filter.</td></tr>
        @endforelse
        </tbody></table></div><div style="margin-top:18px">{{ $attendances->links() }}</div>
    </section>
</div>
@endsection
<style>.filter-month{padding:10px;border:1px solid #dce5de;border-radius:9px;font:inherit}.filter label{display:block;font-size:12px;font-weight:600;margin-bottom:6px}.filter select,.filter input{box-sizing:border-box}.location-links{font-size:11px;line-height:1.6;white-space:nowrap}.location-links a{display:flex;align-items:center;gap:5px;color:#155b45;text-decoration:none}.location-links a:hover{color:#55721a;text-decoration:underline}.location-links svg{width:15px;height:15px;fill:none;stroke:#55721a;stroke-width:1.8;flex:0 0 auto}.location-links span{display:block;color:inherit}@media(max-width:800px){.filter{grid-template-columns:1fr!important}}</style>
